apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nextjs-app
  template:
    metadata:
      labels:
        app: my-nextjs-app
    spec:
      containers:
      - name: my-nextjs-app
        image: fashinadolapo/my-nextjs-app
        ports:
        - containerPort: 80
