name: Build, Test, and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build and test
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build Docker image
        run: docker build -t my-nextjs-app .

      - name: Tag image
        run: |
          #docker tag my-nextjs-app:latest ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
          docker tag my-nextjs-app:latest ${{ secrets.DOCKER_USERNAME }}/my-react-app:v1
      
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      
      - name: Scan with Trivy
        run: |
          trivy image --format table my-nextjs-app
      - name: Push Docker image
        run: |
          docker tag my-nextjs-app ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
          
