name: Build, Test, and Deploy to minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build and test
        run: npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build Docker image
        run: docker build -t my-nextjs-app .

      - name: Tag image
        run: |
          #docker tag my-nextjs-app:latest ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
          docker tag my-nextjs-app:latest ${{ secrets.DOCKER_USERNAME }}/my-react-app:v1
      
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      
      - name: Scan with Trivy
        run: |
          trivy image --format table my-nextjs-app
          
      - name: Push Docker image
        run: |
          docker tag my-nextjs-app ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mkdir -p /usr/local/bin/
          sudo install minikube /usr/local/bin/

      - name: Start Minikube
        run: |
          minikube start --driver=docker

      - name: Apply Kubernetes deployment
        run: |
          kubectl apply -f deployment.yaml

      - name: Apply Kubernetes service
        run: |
          kubectl apply -f service.yaml

      - name: Expose Kubernetes service
        run: |
          kubectl expose deployment my-react-app --type=NodePort --port=80
          
