name: Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project
      run: |
        npm install
        npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-files
        path: ./build

    - name: Setup NGINX service for Linux/macOS/Windows
  # You may pin to the exact commit or the version.
  # uses: nyurik/action-setup-nginx@612ee9cb839ad727832cda16359452e7e14dd521
      uses: nyurik/action-setup-nginx@v1.1

    - name: Deploy
      uses: actions/deploy@v1
      with:
        ssh-host: ${{ secrets.HOST }}
        ssh-port: ${{ secrets.PORT }}
        ssh-username: ${{ secrets.USER_NAME }}
        ssh-password: ${{ secrets.PASSWORD }}
        deploy-path: /var/www/html
        local-path: ./build
      
          
