name: Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build project
      run: |
        npm install
        npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-files
        path: ./build

    - name: Setup NGINX service for Linux/macOS/Windows
  # You may pin to the exact commit or the version.
  # uses: nyurik/action-setup-nginx@612ee9cb839ad727832cda16359452e7e14dd521
      uses: nyurik/action-setup-nginx@v1.1
          
    - name: Deploy to Nginx
      # uses: cross-the-world/ssh-scp-ssh-pipelines@78e864b4890087a58248ff39320406971ca88b89
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        # ssh remote host
        host: ${{ secrets.HOST }}
        # ssh remote port
        port: ${{ secrets.PORT }} # optional
        # ssh remote user
        user: ${{ secrets.USER_NAME }}
        # ssh remote password
        pass: ${{ secrets.PASSWORD }} # optional
        # connection timeout to remote host
        connect_timeout: 30s # optional, default is 30s
        script: |
          mkdir -p /var/www/html
          rm -rf /var/www/html/*
          scp -r ./build-files/* /var/www/html/
          sudo service nginx restart
          
